spring:
  application:
    name: grocery_app

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/grocery_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:tuankiet}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  security:
    jwt:
      # Secret key (chuỗi Hex 256-bit)
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      # Thời gian sống của token (86400000 ms = 24 giờ)
      expiration: 86400000